version: '2.1'

services:
  cdq:
    build: .
    container_name: cdq-app
    ports:
      - "9999:9999"

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.1.4
    user: "$UID:$GID"
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - .//grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost